pipeline:
  identifier: Build_pchakri123_spring_boot_docker_example_1747581516409
  name: Build spring-boot-docker-example
  orgIdentifier: WiproPOC
  projectIdentifier: Chakri_P
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: account.Github
        repoName: pchakri123/spring-boot-docker-example
  stages:
    - stage:
        identifier: build
        name: build
        spec:
          caching:
            enabled: true
          cloneCodebase: true
          execution:
            steps:
              - step:
                  identifier: echo
                  name: echo
                  spec:
                    command: echo hello world
                  timeout: ""
                  type: Run
              - step:
                  identifier: dockerbuild
                  name: docker_build
                  spec:
                    connectorRef: <+input>
                    repo: sample_application
                    tags:
                      - latest
                    caching: true
                  timeout: ""
                  type: BuildAndPushDockerRegistry
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
        type: CI
